#pragma once

#define BLANK_LEVEL 22
#define WHITE_LEVEL 22

#define LINE_COUNT 468

#define LINE_MIN 28
#define LINE_MAX (LINE_MIN + LINE_COUNT)

#define SCREEN_WIDTH 360
#define SCREEN_HEIGTH LINE_COUNT

#define CHARCTER_WIDTH 12
#define CHARCTER_HEIGHT 18

#define SCREEN_BUFFER_WIDTH (SCREEN_WIDTH / 12)
#define SCREEN_BUFFER_HEIGTH (SCREEN_HEIGTH / (CHARCTER_HEIGHT * 2))

#define SCREEN_BUFFER_SIZE (SCREEN_BUFFER_HEIGTH * SCREEN_BUFFER_WIDTH)

#define LINE_BUFFER_SIZE (SCREEN_WIDTH + 2)

void osd_init();
void osd_update();